### ISSUE TITLE
great desire

### ISSUE THREAD

**Issue by wvt-adm** [jhsoftware/sdnspi-DynDns#1]
good morning

the dyndns plugin is a really great thing. since there are more and more use cases for it i wanted to ask if it is possible to extend the http-url-auth to https-url-auth, if possible with a letsencrypt certificate?

greetings and thanks

**Comment by jesperhoy** [comment]
Thank you for your kind words :-) 
As mentioned at the very bottom at https://kb.simpledns.plus/help/a173-dyndns-service-plug-in - it is possible to use HTTPS.
For details on this see https://kb.simpledns.plus/help/a163-how-to-bind-an-ssl-certificate-to-the-http-api (article talks about HTTP API, but it works the same for the DynDNS plug-in).
